// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxeajrngwmyjurtlpsrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4ZWFqcm5nd215anVydGxwc3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzA5MjAsImV4cCI6MjA4NjkwNjkyMH0.Kb_uaMp00O4m49-OnOhzhvA1-xkz8qTsDv5ir_MhKjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});